services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"        # HTTP
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
      - ./acme.json:/acme.json
      - ./traefik-dynamic:/traefik-dynamic
    networks:
      - traefik-net

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    restart: always
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#    networks:
#      - traefik-net

#  jaeger:
#    image: jaegertracing/all-in-one:1.47
#    container_name: jaeger
#    restart: always
#    ports:
#      - "6831:6831/udp"  # Jaeger agent
#      - "16686:16686"    # Jaeger web UI
#      - "14268:14268"    # For tracing data via HTTP
#      - "14250:14250"    # For gRPC
#      - "14269:14269"    # For Prometheus metrics
#    environment:
#      - SPAN_STORAGE_TYPE=badger
#      - METRICS_STORAGE_TYPE=prometheus  # Enable Prometheus
#    networks:
#      - traefik-net


networks:
  traefik-net:
    external: true
