global:
  checkNewVersion: true
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 60s
        writeTimeout: 60s
        idleTimeout: 90s

log:
  level: INFO

api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false   # Only expose services with labels
  file:
    directory: /traefik-dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: p.bapat@maastrichtuniversity.nl
      storage: acme.json
      httpChallenge:
        entryPoint: web
