steps:
  login:
    image: docker
    commands:
      - echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin

  build:
    image: plugins/docker
    depends_on:
      - login
    settings:
      repo: ghcr.io/pranavnbapat/opensearch
      tags: latest
      dockerfile: opensearch-init/Dockerfile
      registry: ghcr.io
      username: $GITHUB_USERNAME
      password: $GITHUB_TOKEN

  init-opensearch:
    image: python:3.11
    environment:
      OPENSEARCH_HOST: opensearch.nexavion.com
    commands:
      - pip install -r requirements.txt
      - python opensearch-init/init-opensearch.py

  deploy:
    image: appleboy/ssh
    settings:
      host: $DEPLOY_HOST
      username: $DEPLOY_USER
      key: $SSH_PRIVATE_KEY
      script: |
        cd /path/to/deployment
        docker compose pull
        docker compose up -d
