steps:
  build:
    image: woodpeckerci/plugin-docker
    settings:
      repo: ghcr.io/pranavnbapat/opensearch
      tags: latest
      dockerfile: opensearch-init/Dockerfile
      registry: ghcr.io
      username: $WOODPECKER_GITHUB_CLIENT
      password: $WOODPECKER_GITHUB_SECRET

  init-opensearch:
    image: python:3.11
    environment:
      OPENSEARCH_HOST: opensearch.nexavion.com
    commands:
      - pip install -r requirements.txt
      - python opensearch-init/init-opensearch.py

  deploy:
    image: appleboy/ssh
    settings:
      host: your-server
      username: your-user
      key: $SSH_PRIVATE_KEY
      script: |
        cd /path/to/deployment
        docker compose pull
        docker compose up -d
