services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-ml1
      - discovery.seed_resolver.timeout=30s
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-ml1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms6g -Xmx6g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
      - node.attr.zone=zone1
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - thread_pool.write.size=16
      - thread_pool.search.size=24
      - network.host=0.0.0.0
      - gateway.recover_after_nodes=2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensearch.rule=Host(`opensearch.nexavion.com`)"
      - "traefik.http.routers.opensearch.entrypoints=websecure"
      - "traefik.http.routers.opensearch.tls=true"
      - "traefik.http.routers.opensearch.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensearch.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      - traefik-net

  opensearch-node2:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-ml1
      - discovery.seed_resolver.timeout=30s
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms6g -Xmx6g
      - node.attr.zone=zone2
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-ml1
      - thread_pool.write.size=16
      - thread_pool.search.size=24
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
      - network.host=0.0.0.0
      - gateway.recover_after_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - traefik-net

  opensearch-ml1:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch-ml1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-ml1
      - node.roles=ml
      - discovery.seed_hosts=opensearch-node1,opensearch-node2,opensearch-ml1
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2,opensearch-ml1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - plugins.ml_commons.only_run_on_ml_node=true
      - plugins.ml_commons.task_dispatch_policy=least_load
      - plugins.ml_commons.max_ml_task_per_node=30
      - plugins.ml_commons.max_model_on_node=30
      - plugins.ml_commons.allow_registering_model_via_url=true
      - plugins.ml_commons.allow_registering_model_via_local_file=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-ml1:/usr/share/opensearch/data
    networks:
      - traefik-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch.nexavion.com"]
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboards.rule=Host(`dashboard.opensearch.nexavion.com`)"
      - "traefik.http.routers.dashboards.entrypoints=websecure"
      - "traefik.http.routers.dashboards.tls=true"
      - "traefik.http.routers.dashboards.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboards.loadbalancer.server.port=5601"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-net
    restart: unless-stopped

volumes:
  opensearch-data1:
    driver: local
  opensearch-data2:
    driver: local
  opensearch-ml1:
    driver: local

networks:
  traefik-net:
    external: true
