services:
  opensearchtest-node1:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearchtest-node1
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-node1
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2,opensearchtest-ml1,opensearchtest-ml2
      - discovery.seed_resolver.timeout=30s
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
      - node.attr.zone=zone1
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - thread_pool.write.size=16
      - thread_pool.search.size=24
      - network.host=0.0.0.0
      - gateway.recover_after_data_nodes=2
      - gateway.expected_data_nodes=2
      - gateway.recover_after_time=5m
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensearchtest.rule=Host(`opensearchtest.nexavion.com`)"
      - "traefik.http.routers.opensearchtest.entrypoints=websecure"
      - "traefik.http.routers.opensearchtest.tls=true"
      - "traefik.http.routers.opensearchtest.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensearchtest.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    volumes:
      - opensearchtest-data1:/usr/share/opensearch/data
    networks:
      - traefik-test-net

  opensearchtest-node2:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearchtest-node2
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-node2
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2,opensearchtest-ml1,opensearchtest-ml2
      - discovery.seed_resolver.timeout=30s
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - node.attr.zone=zone2
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - thread_pool.write.size=16
      - thread_pool.search.size=24
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
      - network.host=0.0.0.0
      - gateway.recover_after_data_nodes=2
      - gateway.expected_data_nodes=2
      - gateway.recover_after_time=5m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    volumes:
      - opensearchtest-data2:/usr/share/opensearch/data
    networks:
      - traefik-test-net

  opensearchtest-ml1:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearchtest-ml1
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-ml1
      - node.roles=ml
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2,opensearchtest-ml1,opensearchtest-ml2
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - plugins.ml_commons.only_run_on_ml_node=true
      - plugins.ml_commons.task_dispatch_policy=least_load
      - plugins.ml_commons.max_ml_task_per_node=30
      - plugins.ml_commons.max_model_on_node=30
      - plugins.ml_commons.allow_registering_model_via_url=true
      - plugins.ml_commons.allow_registering_model_via_local_file=true
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - opensearchtest-node1
      - opensearchtest-node2
    volumes:
      - opensearchtest-ml1:/usr/share/opensearch/data
#      - ./performance-analyzer-config/opensearch-performance-analyzer:/usr/share/opensearch/config/opensearch-performance-analyzer:ro
    networks:
      - traefik-test-net

  opensearchtest-ml2:
    image: opensearchproject/opensearch:3.0.0
    container_name: opensearchtest-ml2
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-ml2
      - node.roles=ml
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2,opensearchtest-ml1,opensearchtest-ml2
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - plugins.ml_commons.only_run_on_ml_node=true
      - plugins.ml_commons.task_dispatch_policy=least_load
      - plugins.ml_commons.max_ml_task_per_node=30
      - plugins.ml_commons.max_model_on_node=30
      - plugins.ml_commons.allow_registering_model_via_url=true
      - plugins.ml_commons.allow_registering_model_via_local_file=true
      - plugins.security.disabled=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.ssl.transport.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    depends_on:
      - opensearchtest-node1
      - opensearchtest-node2
    volumes:
      - opensearchtest-ml2:/usr/share/opensearch/data
      - ./performance-analyzer-config/opensearch-performance-analyzer:/usr/share/opensearch/config/opensearch-performance-analyzer:ro
    networks:
      - traefik-test-net

  opensearchtest-dashboards:
    image: opensearchproject/opensearch-dashboards:3.0.0
    container_name: opensearchtest-dashboards
    environment:
      - OPENSEARCH_HOSTS=["https://opensearchtest.nexavion.com"]
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboardstest.rule=Host(`dashboard.opensearchtest.nexavion.com`)"
      - "traefik.http.routers.dashboardstest.entrypoints=websecure"
      - "traefik.http.routers.dashboardstest.tls=true"
      - "traefik.http.routers.dashboardstest.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboardstest.loadbalancer.server.port=5601"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - opensearchtest-node1
    networks:
      - traefik-test-net
    restart: unless-stopped

volumes:
  opensearchtest-data1:
    driver: local
  opensearchtest-data2:
    driver: local
  opensearchtest-ml1:
    driver: local
  opensearchtest-ml2:
    driver: local

networks:
  traefik-test-net:
    external: true
