services:
  opensearchtest-node1:
    image: opensearchproject/opensearch:3
    container_name: opensearchtest-node1
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-node1
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2
      - discovery.seed_resolver.timeout=30s
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - node.attr.zone=zone1
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - plugins.security.disabled=false
      - plugins.security.ssl.transport.enabled=true
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/certs/admin.pem
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/certs/admin-key.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/root-ca.pem
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/certs/admin.pem
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/certs/admin-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/root-ca.pem
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - thread_pool.write.size=16
      - thread_pool.search.size=24
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.opensearchtest.rule=Host(`opensearchtest.nexavion.com`)"
      - "traefik.http.routers.opensearchtest.entrypoints=websecure"
      - "traefik.http.routers.opensearchtest.tls=true"
      - "traefik.http.routers.opensearchtest.tls.certresolver=letsencrypt"
      - "traefik.http.services.opensearchtest.loadbalancer.server.port=9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    command: ["/bin/bash", "-c", "/usr/share/opensearch/entrypoint.sh"]
    volumes:
      - ./certs:/usr/share/opensearch/config/certs:ro
      - ./securityconfig:/usr/share/opensearch/config/securityconfig:ro
      - ./entrypoint.sh:/usr/share/opensearch/entrypoint.sh:ro
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
    networks:
      - traefik-test-net

  opensearchtest-node2:
    image: opensearchproject/opensearch:3
    container_name: opensearchtest-node2
    environment:
      - cluster.name=opensearchtest-cluster
      - node.name=opensearchtest-node2
      - node.roles=cluster_manager,data,ingest
      - discovery.seed_hosts=opensearchtest-node1,opensearchtest-node2
      - discovery.seed_resolver.timeout=30s
      - cluster.initial_cluster_manager_nodes=opensearchtest-node1,opensearchtest-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - node.attr.zone=zone2
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - OPENSEARCH_USERNAME=admin
      - plugins.security.disabled=false
      - plugins.security.ssl.transport.enabled=true
      - plugins.security.ssl.transport.pemcert_filepath=/usr/share/opensearch/config/certs/admin.pem
      - plugins.security.ssl.transport.pemkey_filepath=/usr/share/opensearch/config/certs/admin-key.pem
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/root-ca.pem
      - plugins.security.ssl.http.enabled=true
      - plugins.security.ssl.http.pemcert_filepath=/usr/share/opensearch/config/certs/admin.pem
      - plugins.security.ssl.http.pemkey_filepath=/usr/share/opensearch/config/certs/admin-key.pem
      - plugins.security.ssl.http.pemtrustedcas_filepath=/usr/share/opensearch/config/certs/root-ca.pem
      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
      - cluster.routing.allocation.awareness.attributes=zone
      - cluster.routing.allocation.awareness.force.zone.values=zone1,zone2
      - thread_pool.write.size=16
      - thread_pool.search.size=24
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
    volumes:
      - ./certs:/usr/share/opensearch/config/certs:ro
      - ./securityconfig:/usr/share/opensearch/config/securityconfig:ro
      - ./entrypoint.sh:/usr/share/opensearch/entrypoint.sh:ro
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
    networks:
      - traefik-test-net

#  opensearchtest-dashboards:
#    image: opensearchproject/opensearch-dashboards:3
#    container_name: opensearchtest-dashboards
#    environment:
#      - OPENSEARCH_HOSTS=["https://opensearchtest.nexavion.com"]
#      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
#      - OPENSEARCH_USERNAME=admin
#      - OPENSEARCH_PASSWORD=${OPENSEARCHTEST_ADMIN_PASSWORD}
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.dashboardstest.rule=Host(`dashboard.opensearchtest.nexavion.com`)"
#      - "traefik.http.routers.dashboardstest.entrypoints=websecure"
#      - "traefik.http.routers.dashboardstest.tls=true"
#      - "traefik.http.routers.dashboardstest.tls.certresolver=letsencrypt"
#      - "traefik.http.services.dashboardstest.loadbalancer.server.port=5601"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:5601"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    depends_on:
#      - opensearchtest-node1
#    networks:
#      - traefik-test-net
#    restart: unless-stopped

volumes:
  opensearchtest-data1:
    driver: local
  opensearchtest-data2:
    driver: local

networks:
  traefik-test-net:
    external: true
